// Official English DCI-37 wording and scoring metadata.
// Source and permission statement: Bodenmann (2008), as reproduced in
// Simmons & Lehmann (2012). The source states that no further permission is
// needed for use or reproduction from Guy Bodenmann. Preserve the attribution.
window.CPQ_DCI_ITEM_BANK = {
  version: 'DCI-37 · Bodenmann (2008)',
  language: 'official English with unofficial Chinese reading aid',
  translationStatus: 'Chinese wording is an unvalidated reading aid produced for this interface; official English wording remains the reference.',
  authorizationConfirmed: true,
  attribution: 'Copyright © 2008 Guy Bodenmann. Reproduced with permission. Cite Bodenmann (2008).',
  sourceUrl: 'https://www.researchgate.net/profile/Guy-Bodenmann/publication/323285418_Dyadic_Coping_Inventory/links/5a901eeea6fdccecff00ce52/Dyadic-Coping-Inventory.pdf',
  items: [
    { id: 1, zh: '我会让伴侣知道，我很感谢对方在实际事务上的支持、建议或帮助。', text: 'I let my partner know that I appreciate his/her practical support, advice, or help.', section: 'How you communicate your stress to your partner', subscale: 'selfStressCommunication', reverse: false },
    { id: 2, zh: '当我事情太多时，我会请伴侣替我做一些事。', text: 'I ask my partner to do things for me when I have too much to do.', section: 'How you communicate your stress to your partner', subscale: 'selfStressCommunication', reverse: false },
    { id: 3, zh: '当我状态不好或遇到问题时，我会通过自己的行为让伴侣看出来。', text: 'I show my partner through my behavior when I am not doing well or when I have problems.', section: 'How you communicate your stress to your partner', subscale: 'selfStressCommunication', reverse: false },
    { id: 4, zh: '我会坦率地告诉伴侣我的感受，并表示我希望得到对方的支持。', text: 'I tell my partner openly how I feel and that I would appreciate his/her support.', section: 'How you communicate your stress to your partner', subscale: 'selfStressCommunication', reverse: false },
    { id: 5, zh: '伴侣会对我表现出共情和理解。', text: 'My partner shows empathy and understanding to me.', section: 'What your partner does when you are feeling stressed', subscale: 'partnerSupportive', reverse: false },
    { id: 6, zh: '伴侣会表示对方站在我这一边。', text: 'My partner expresses that he/she is on my side.', section: 'What your partner does when you are feeling stressed', subscale: 'partnerSupportive', reverse: false },
    { id: 7, zh: '伴侣会责怪我没有把压力应对得足够好。', text: 'My partner blames me for not coping well enough with stress.', section: 'What your partner does when you are feeling stressed', subscale: 'partnerNegative', reverse: true },
    { id: 8, zh: '伴侣会帮助我从不同角度看待有压力的处境。', text: 'My partner helps me to see stressful situations in a different light.', section: 'What your partner does when you are feeling stressed', subscale: 'partnerSupportive', reverse: false },
    { id: 9, zh: '伴侣会倾听我，并给我机会说出真正困扰我的事情。', text: 'My partner listens to me and gives me the opportunity to communicate what really bothers me.', section: 'What your partner does when you are feeling stressed', subscale: 'partnerSupportive', reverse: false },
    { id: 10, zh: '伴侣不会认真看待我的压力。', text: 'My partner does not take my stress seriously.', section: 'What your partner does when you are feeling stressed', subscale: 'partnerNegative', reverse: true },
    { id: 11, zh: '伴侣会提供支持，但显得不情愿，也没有积极性。', text: 'My partner provides support, but does so unwillingly and unmotivated.', section: 'What your partner does when you are feeling stressed', subscale: 'partnerNegative', reverse: true },
    { id: 12, zh: '为了帮助我，伴侣会接手一些通常由我完成的事情。', text: 'My partner takes on things that I normally do in order to help me out.', section: 'What your partner does when you are feeling stressed', subscale: 'partnerDelegated', reverse: false },
    { id: 13, zh: '伴侣会帮助我分析情境，使我能更好地面对问题。', text: 'My partner helps me analyze the situation so that I can better face the problem.', section: 'What your partner does when you are feeling stressed', subscale: 'partnerSupportive', reverse: false },
    { id: 14, zh: '当我太忙时，伴侣会帮我分担。', text: 'When I am too busy, my partner helps me out.', section: 'What your partner does when you are feeling stressed', subscale: 'partnerDelegated', reverse: false },
    { id: 15, zh: '当我有压力时，伴侣往往会退开。', text: 'When I am stressed, my partner tends to withdraw.', section: 'What your partner does when you are feeling stressed', subscale: 'partnerNegative', reverse: true },
    { id: 16, zh: '伴侣会让我知道，对方很感谢我在实际事务上的支持、建议或帮助。', text: 'My partner lets me know that he/she appreciates my practical support, advice, or help.', section: 'How your partner communicates when he/she is feeling stressed', subscale: 'partnerStressCommunication', reverse: false },
    { id: 17, zh: '当伴侣事情太多时，对方会请我替其做一些事。', text: 'My partner asks me to do things for him/her when he/she has too much to do.', section: 'How your partner communicates when he/she is feeling stressed', subscale: 'partnerStressCommunication', reverse: false },
    { id: 18, zh: '当伴侣状态不好或遇到问题时，对方会通过自己的行为让我看出来。', text: 'My partner shows me through his/her behavior that he/she is not doing well or when he/she has problems.', section: 'How your partner communicates when he/she is feeling stressed', subscale: 'partnerStressCommunication', reverse: false },
    { id: 19, zh: '伴侣会坦率地告诉我对方的感受，并表示希望得到我的支持。', text: 'My partner tells me openly how he/she feels and that he/she would appreciate my support.', section: 'How your partner communicates when he/she is feeling stressed', subscale: 'partnerStressCommunication', reverse: false },
    { id: 20, zh: '我会对伴侣表现出共情和理解。', text: 'I show empathy and understanding to my partner.', section: 'What you do when your partner communicates stress', subscale: 'selfSupportive', reverse: false },
    { id: 21, zh: '我会向伴侣表示我站在对方这一边。', text: 'I express to my partner that I am on his/her side.', section: 'What you do when your partner communicates stress', subscale: 'selfSupportive', reverse: false },
    { id: 22, zh: '我会责怪伴侣没有把压力应对得足够好。', text: 'I blame my partner for not coping well enough with stress.', section: 'What you do when your partner communicates stress', subscale: 'selfNegative', reverse: true },
    { id: 23, zh: '我会告诉伴侣事情没有那么糟，并帮助对方从不同角度看待这一处境。', text: 'I tell my partner that his/her stress is not that bad and help him/her to see the situation in a different light.', section: 'What you do when your partner communicates stress', subscale: 'selfSupportive', reverse: false },
    { id: 24, zh: '我会倾听伴侣，并给对方空间和时间说出真正困扰自己的事情。', text: 'I listen to my partner and give him/her space and time to communicate what really bothers him/her.', section: 'What you do when your partner communicates stress', subscale: 'selfSupportive', reverse: false },
    { id: 25, zh: '我不会认真看待伴侣的压力。', text: 'I do not take my partner\u2019s stress seriously.', section: 'What you do when your partner communicates stress', subscale: 'selfNegative', reverse: true },
    { id: 26, zh: '当伴侣有压力时，我往往会退开。', text: 'When my partner is stressed I tend to withdraw.', section: 'What you do when your partner communicates stress', subscale: 'selfNegative', reverse: true },
    { id: 27, zh: '我会提供支持，但很不情愿、缺乏积极性，因为我认为伴侣应该自己应对这些问题。', text: 'I provide support, but do it so unwillingly and unmotivated because I think that he/she should cope with his/her problems on his/her own.', section: 'What you do when your partner communicates stress', subscale: 'selfNegative', reverse: true },
    { id: 28, zh: '为了帮助伴侣，我会接手一些通常由对方完成的事情。', text: 'I take on things that my partner would normally do in order to help him/her out.', section: 'What you do when your partner communicates stress', subscale: 'selfDelegated', reverse: false },
    { id: 29, zh: '我会和伴侣一起客观分析情境，帮助对方理解并改变问题。', text: 'I try to analyze the situation together with my partner in an objective manner and help him/her to understand and change the problem.', section: 'What you do when your partner communicates stress', subscale: 'selfSupportive', reverse: false },
    { id: 30, zh: '当伴侣觉得事情太多时，我会帮对方分担。', text: 'When my partner feels he/she has too much to do, I help him/her out.', section: 'What you do when your partner communicates stress', subscale: 'selfDelegated', reverse: false },
    { id: 31, zh: '我们会一起应对问题，并寻找切实可行的解决办法。', text: 'We try to cope with the problem together and search for ascertained solutions.', section: 'What you and your partner do when you are both feeling stressed', subscale: 'common', reverse: false },
    { id: 32, zh: '我们会认真讨论这个问题，并仔细考虑需要做些什么。', text: 'We engage in a serious discussion about the problem and think through what has to be done.', section: 'What you and your partner do when you are both feeling stressed', subscale: 'common', reverse: false },
    { id: 33, zh: '我们会帮助彼此正确看待问题，并从新的角度理解它。', text: 'We help one another to put the problem in perspective and see it in a new light.', section: 'What you and your partner do when you are both feeling stressed', subscale: 'common', reverse: false },
    { id: 34, zh: '我们会通过按摩、一起洗澡或一起听音乐等方式帮助彼此放松。', text: 'We help each other relax with such things like massage, taking a bath together, or listening to music together.', section: 'What you and your partner do when you are both feeling stressed', subscale: 'common', reverse: false },
    { id: 35, zh: '我们会彼此亲昵、做爱，并尝试以这种方式应对压力。', text: 'We are affectionate to each other, make love and try that way to cope with stress.', section: 'What you and your partner do when you are both feeling stressed', subscale: 'common', reverse: false },
    { id: 36, zh: '我对伴侣给予我的支持，以及我们共同应对压力的方式感到满意。', text: 'I am satisfied with the support I receive from my partner and the way we deal with stress together.', section: 'How you evaluate your coping as a couple', subscale: 'evaluation', reverse: false },
    { id: 37, zh: '我对伴侣给予我的支持感到满意，并认为我们作为一对伴侣共同应对压力的方式是有效的。', text: 'I am satisfied with the support I receive from my partner and I find as a couple, the way we deal with stress together is effective.', section: 'How you evaluate your coping as a couple', subscale: 'evaluation', reverse: false }
  ]
};
